apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favorites-service
  template:
    metadata:
      labels:
        app: favorites-service
    spec:
      containers:
        - name: favorites-service
          image: markogartnar/soundscape-favorites:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8001
          env:
            - name: SERVICE_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: favorites-secrets
                  key: AUTH0_DOMAIN
            - name: SERVICE_AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: favorites-secrets
                  key: AUTH0_AUDIENCE
            - name: SERVICE_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: favorites-secrets
                  key: POSTGRES_URL
            - name: SERVICE_METADATA_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: favorites-secrets
                  key: METADATA_SERVICE_URL
          livenessProbe:
            httpGet:
              path: /livez
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
