apiVersion: v1
kind: Service
metadata:
  name: favorites-public-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: favorites-service
