apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
        - name: upload-service
          image: markogartnar/soundscape-upload:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: upload-secrets
                  key: AUTH0_DOMAIN
            - name: SERVICE_AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: upload-secrets
                  key: AUTH0_AUDIENCE
            - name: SERVICE_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: upload-secrets
                  key: POSTGRES_URL
            - name: SERVICE_AZURE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: upload-secrets
                  key: AZURE_ACCOUNT_NAME
            - name: SERVICE_AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: upload-secrets
                  key: AZURE_ACCOUNT_KEY
            - name: SERVICE_AZURE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: upload-secrets
                  key: AZURE_CONTAINER_NAME
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
