apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
        - name: upload-service
          image: markogartnar/soundscape-upload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: SERVICE_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH0_DOMAIN
            - name: SERVICE_AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH0_AUDIENCE
            - name: SERVICE_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_URL
          livenessProbe:
            httpGet:
              path: /livez
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
