_format_version: "3.0"
services:
  - name: metadata-service
    url: http://metadata-service:3000
    routes:
      - name: metadata-service
        paths:
          - /metadata
  - name: users-service
    url: http://users-service:3000
    routes:
      - name: users-service
        paths:
          - /users
