name: ⬣ Build & Test Favorites Service
on:
  push:
    branches:
      - main
    paths:
      - "services/favorites/**"
      - "shared/**"
  pull_request:
    paths:
      - "services/favorites/**"
      - "shared/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"

      - name: Build
        run: go build -v ./...
        working-directory: services/favorites
      - name: Test with the Go CLI
        run: go test ./...
        working-directory: services/favorites
