name: Publish & Deploy Upload Service

on:
  push:
    branches:
      - main
    paths:
      - "services/upload/**"
      - "shared/**"
  # TODO: remove/comment out this
  pull_request:
    branches:
      - main
    paths:
      - "services/upload/**"
      - "shared/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./services/upload/Dockerfile
          push: true
          tags: markogartnar/soundscape-upload:latest

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push # Wait for the image build job to finish

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # Authenticate to Azure
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Configure kubectl to use AKS
      - name: Configure kubectl
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic upload-secrets \
            --from-literal=AUTH0_DOMAIN="${{ secrets.AUTH0_DOMAIN }}" \
            --from-literal=AUTH0_AUDIENCE="${{ secrets.AUTH0_AUDIENCE }}" \
            --from-literal=POSTGRES_URL="${{ secrets.METADATA_POSTGRES_URL }}" \
            --from-literal=AZURE_ACCOUNT_NAME="${{ secrets.AZURE_ACCOUNT_NAME }}" \
            --from-literal=AZURE_ACCOUNT_KEY="${{ secrets.AZURE_ACCOUNT_KEY }}" \
            --from-literal=AZURE_CONTAINER_NAME="${{ secrets.AZURE_CONTAINER_NAME }}" \
            --dry-run=client -o yaml | kubectl apply -f -
      # Deploy to AKS
      - name: Apply Kubernetes manifests
        working-directory: ./services/upload
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/public-svc.yaml  # Ensure LoadBalancer is created
          kubectl apply -f k8s/hpa.yaml
          kubectl rollout restart deployment upload-service

      - name: Confirm Deployment
        run: |
          kubectl rollout status deployment/upload-service --timeout=60s
