name: ⬣ Users Service

on:
  push:
    branches:
      - main
    paths:
      - "services/user/**"
      - "pkg/**"
      - ".github/workflows/users-service.yml"
  pull_request:
    paths:
      - "users-service/**"
      - "pkg/**"
      - ".github/workflows/users-service.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"

      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
